module.exports = (sequelize, Sequelize) => {
    const Char = sequelize.define("chars", {
        id: {
            type: Sequelize.INTEGER,
            autoIncrement: true,
            allowNull: false,
            primaryKey: true
        },
        name: { type: Sequelize.STRING, allowNull: false },
        age: { type: Sequelize.INTEGER, allowNull: false },
        origem: { type: Sequelize.STRING, allowNull: false },
        nationality: { type: Sequelize.STRING, allowNull: false },
        patente: { type: Sequelize.STRING, allowNull: false },
        status_vida: { type: Sequelize.INTEGER, allowNull: false },
        nex: { type: Sequelize.INTEGER, allowNull: false },
        life_points: { type: Sequelize.INTEGER, allowNull: false },
        pe: { type: Sequelize.INTEGER, allowNull: false },
        sanity: { type: Sequelize.INTEGER, allowNull: false },
        afilicao: { type: Sequelize.STRING, allowNull: false },
        agilidade: { type: Sequelize.INTEGER, allowNull: false },
        forca: { type: Sequelize.INTEGER, allowNull: false },
        intelecto: { type: Sequelize.INTEGER, allowNull: false },
        presenca: { type: Sequelize.INTEGER, allowNull: false },
        vigor: { type: Sequelize.INTEGER, allowNull: false },
        acrobacia: { type: Sequelize.INTEGER, allowNull: false },
        adestramento: { type: Sequelize.INTEGER, allowNull: false },
        artes: { type: Sequelize.INTEGER, allowNull: false },
        atletismo: { type: Sequelize.INTEGER, allowNull: false },
        atualidades: { type: Sequelize.INTEGER, allowNull: false },
        ciencias: { type: Sequelize.INTEGER, allowNull: false },
        crime: { type: Sequelize.INTEGER, allowNull: false },
        diplomacia: { type: Sequelize.INTEGER, allowNull: false },
        enganacao: { type: Sequelize.INTEGER, allowNull: false },
        fortitude: { type: Sequelize.INTEGER, allowNull: false },
        furtividade: { type: Sequelize.INTEGER, allowNull: false },
        iniciativa: { type: Sequelize.INTEGER, allowNull: false },
        intimidacao: { type: Sequelize.INTEGER, allowNull: false },
        intuicao: { type: Sequelize.INTEGER, allowNull: false },
        investigacao: { type: Sequelize.INTEGER, allowNull: false },
        luta: { type: Sequelize.INTEGER, allowNull: false },
        medicina: { type: Sequelize.INTEGER, allowNull: false },
        ocultimo: { type: Sequelize.INTEGER, allowNull: false },
        percepcao: { type: Sequelize.INTEGER, allowNull: false },
        pilotagem: { type: Sequelize.INTEGER, allowNull: false },
        pontaria: { type: Sequelize.INTEGER, allowNull: false },
        profissao: { type: Sequelize.INTEGER, allowNull: false },
        reflexos: { type: Sequelize.INTEGER, allowNull: false },
        sobrevivencia: { type: Sequelize.INTEGER, allowNull: false },
        tatica: { type: Sequelize.INTEGER, allowNull: false },
        tecnologia: { type: Sequelize.INTEGER, allowNull: false },
        vontade: { type: Sequelize.INTEGER, allowNull: false },
        owner_id: { type: Sequelize.INTEGER, allowNull: false },
    }, {
        freezeTableName: true,
        createdAt: false,
        updatedAt: false
    })
    return Char
}